FROM node:20-alpine

# Native build tooling for serial dependencies
RUN apk add --no-cache --virtual .build-deps python3 make g++ linux-headers

WORKDIR /srv

COPY warema-bridge/rootfs/srv/package-lock.json ./
COPY warema-bridge/rootfs/srv/package.json ./

RUN npm ci && apk del --no-cache --purge .build-deps && rm -rf /root/.npm /root/.cache

COPY warema-bridge/rootfs/srv ./

ENTRYPOINT ["/usr/local/bin/node", "/srv/bridge.js"]
